### ISSUE TITLE
Support for organisations

### ISSUE THREAD

**Issue by jussih** [CityOfHameenlinna/respa#2]
In Hämeenlinna Respa will be used by multiple organisations.

* Units must be associated to organisations
* Organisations must support some theming variables

**Comment by jussih** [comment]
Organisation should have at least the following attributes:
- `name` (Name displayed to users in UI)
- `min_color` (color attributes are for theming the UI. CharFields containing color codes.)
- `low_color`
- `high_color`
- `max_color`
- `logo` (organisation logo image)
- `latitude`
- `longitude` (gps coordinates of the organisation, such as the center of a municipality)

Unit should have foreign key to organisation.

User should have a foreign key to organisation.

All relevant API endpoints need to implement a new filter for selecting only stuff that belongs to a certain Organisation by org id. (At least, Unit, Resource, Purpose, Reservation, maybe some others.)

Purpose list should only return Purposes which have > 0 Resources.

**Comment by jussih** [comment]
There is also an existing organisation app from helsinki: https://github.com/City-of-Helsinki/django-orghierarchy

**Comment by silenatte** [comment]
This has been resolved with different Respa or other reservation system instances. Closing.
