### ISSUE TITLE
Support for payments

### ISSUE THREAD

**Issue by jussih** [CityOfHameenlinna/respa#3]
Support is needed for payments while making a reservation.

**Comment by jussih** [comment]
For payments support there should be a generic django app for payments-related data, `respa_payments`. The app should contain at least the following models:

- `Purchase`: purchase and payment related data, this model currently exists in hmlvaraus. Add at least an attribute declaring which payment backend has been used.
- (Optional) `PurchaseState`: It would be nice to save all purchase state changes in the database for auditing. Creating this would need a data migration from hmlvaraus. This would need at least the following attributes:
  - `user`: who caused the state to change
  - `purchase`: fk to the Purchase that is the target of the state change
  - `timestamp`
  - `previous_state`: what was the previous state, such as `CREATED`
  - `new_state`:  what is the new state, such as `PAID` or `CANCELED`
- `SKU`: a model representing a "sellable" item with payment data
  - `resource`: fk to Resource, the item being "sold"
  - `price`: price per reservation

`respa_payments` does not include any payment processor related code. It offers an internal API for creating and modifying Purchases, for example to set Purchase to a paid state. Payment processor modules can then be implemented using the API.

Implement suomi.fi payments as a payment processor module. It will be a django app containing all suomi.fi specific code, such as API endpoints for the payment flow from the UI and callback API urls for suomi.fi payment platform. Manipulation of Purchases happens via the internal API provided by `respa_payments`. Most of this code exists already in hmlvaraus. Berth reservation frontend might need changes if the payment API urls change.

**Comment by turtommy** [comment]
Must be able to manage price and other purchase information through sysadmin.

**Comment by silenatte** [comment]
This has been implemented.
